# This is a basic workflow to help you get started with Actions
name: Deploy to Dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the main "main" branch, this will also work for merging pull requests into "main"
  push:
    tags: [ "debug*" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "ftp-deploy"
    ftp-deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout latest changes
              uses: actions/checkout@v3

            # Here is the deployment action
            - name: Upload from output to a remote server via FTP
              uses: modern-dev/ftp-mirror@v2
              with:
                server: ftp.sblik.com
                user: ${{ secrets.FTP_USERNAME }}
                password: ${{ secrets.FTP_PASSWORD }}
                local_dir: "./debug"
                remote_dir: "./wp-content/debug_log"
                delete: "false"
