# This is a basic workflow to help you get started with Actions
name: Deploy to Dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the main "main" branch, this will also work for merging pull requests into "main"
  push:
    tags: [ "dev*" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ftp-deploy"
  ftp-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout latest changes
        uses: actions/checkout@v3


      # Deploy PLUGIN files to server via FTP
      - name: Deploy plugin changes via ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.sblik.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}         
          server-dir: /wp-content/plugins/bs-divorce-site/
          local-dir: ./src_plugin/
          exclude: |
            **/exclude/**
            
      # Deploy PDF TEMPLATE files to server via FTP
      - name: Deploy PDF template changes via ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.sblik.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}         
          server-dir: /wp-content/uploads/PDF_EXTENDED_TEMPLATES/
          local-dir: ./src_uploads/
          exclude: |
            **/exclude/*
      - name: Install lftp
        run: sudo apt install lftp
      - name: download debug
        run: lftp -c "set ssl:verify-certificate false; open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp.sblik.com; mirror -n -v /wp-content/debug_log debug"